name: Deploy Trigger

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger spinthetrack-app deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_FOR_DEPLOYMENT }}
          repository: SpinTheTrack-Studio/spinthetrack-app
          event-type: trigger-deploy
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'